// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN6t_tPLUmrJ2bobsPN4tuAayyvtHnTZM',
    appId: '1:353430566381:web:780cf98915ee4c028763e4',
    messagingSenderId: '353430566381',
    projectId: 'parking-system-24fe9',
    authDomain: 'parking-system-24fe9.firebaseapp.com',
    storageBucket: 'parking-system-24fe9.firebasestorage.app',
    measurementId: 'G-MV86YG5NHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCxhccVN83g0nSS7RwuJCfaOZ6pLo1So',
    appId: '1:353430566381:android:171e8054f4f0fae48763e4',
    messagingSenderId: '353430566381',
    projectId: 'parking-system-24fe9',
    storageBucket: 'parking-system-24fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQDNgKN9Uet--EHbVPL189RLO16flBxk',
    appId: '1:353430566381:ios:89cedfc6508721178763e4',
    messagingSenderId: '353430566381',
    projectId: 'parking-system-24fe9',
    storageBucket: 'parking-system-24fe9.firebasestorage.app',
    iosBundleId: 'com.example.parkingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQDNgKN9Uet--EHbVPL189RLO16flBxk',
    appId: '1:353430566381:ios:89cedfc6508721178763e4',
    messagingSenderId: '353430566381',
    projectId: 'parking-system-24fe9',
    storageBucket: 'parking-system-24fe9.firebasestorage.app',
    iosBundleId: 'com.example.parkingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN6t_tPLUmrJ2bobsPN4tuAayyvtHnTZM',
    appId: '1:353430566381:web:15f3ca6e0e2e97048763e4',
    messagingSenderId: '353430566381',
    projectId: 'parking-system-24fe9',
    authDomain: 'parking-system-24fe9.firebaseapp.com',
    storageBucket: 'parking-system-24fe9.firebasestorage.app',
    measurementId: 'G-8F01L1ZVD4',
  );
}
